apiVersion: v1
kind: Service
metadata:
  name: security-server-sidecar-fi
  labels:
    run: security-server-sidecar-fi
spec:
  type: LoadBalancer
  ports:
  - port: 5500
    targetPort: 5500
    protocol: TCP
    name: messaging
  - port: 5577
    targetPort: 5577
    protocol: TCP
    name: ocsp
  selector:
    run: security-server-sidecar-fi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: security-server-sidecar-fi
  name: security-server-sidecar-fi
spec:
  replicas: 1
  selector:
    matchLabels:
      run: security-server-sidecar-fi
  template:
    metadata:
      labels:
        run: security-server-sidecar-fi
    spec:
      containers:
      - image: niis/xroad-security-server-sidecar:latest-fi
        name: security-server-sidecar-fi
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 500m
        env:
        - name: XROAD_TOKEN_PIN
          value: "12345"
        - name: XROAD_ADMIN_USER
          value: "xrd"
        - name: XROAD_ADMIN_PASSWORD
          value: "secret"
        - name: XROAD_DB_HOST
          value: "127.0.0.1"
        - name: XROAD_DB_PORT
          value: "5432"
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 4000
        - containerPort: 5500
        - containerPort: 5577
        - containerPort: 5588
